### ISSUE TITLE
Brainlean freezes with the new source code (4 days ago)

### ISSUE THREAD

**Issue by shapiro85** [amchess/BrainLearn#12]
Hi Amchess,
The new source code (4 days ago) Causes Brainlean to freeze for (10-98 seconds) before playing the first move. and some times during the game
I tested it with different chess GUI ( Fritz, Cutechess and Bankisa) and on different pcs.
I had no issues with Brainlearn's source code (9 days ago)
this issue is well know for long time with Eman engines
I hope you can fix this issue to make Brainlean use-able
best wishes

**Comment by amchess** [comment]
Now is it good?

**Comment by shapiro85** [comment]
Hi Andrea,
the issue is not solved.
Brainlean 9.1 loads and plays faster the first move without or with small size Experience.bin.
it gets worse with big size Experience.bin (bigger than 50 MB)
I tested it with different chess GUI ( Fritz, Cutechess and Bankisa) and on different pcs.
