### ISSUE TITLE
separate best move on/off for each book

### ISSUE THREAD

**Issue by neles666** [amchess/BrainLearn#14]
Hi, is it possible to add best move selector for each opening book? Idea is simple - first book play NO best move for basic variability (c4, d4, e4, nf3) then main book best move ON  for best moves. With this possibility engine doesnt play same openings and also keep the best lines. If possible third opening book would be great. Idea is simple - 1 book for basic opening variability, 2 book for patches, 3 main big library of moves. It means if I have fishbooster.bin 2gb library, when i make update, i can send just only patch.bin with few kb and new deeper moves

**Comment by amchess** [comment]
I'm in strong doubt about this.
Bin file format, in my opinion, is not as good as ctg chessbase format.
Bin books can be converted in pgn and then in ctg (or other gui format)
I'm also tempted to completely eliminate those options to not slow down the engine and confer only on the gui
the opening book management.
