### ISSUE TITLE
No EvalFile on UCI Option?

### ISSUE THREAD

**Issue by jackindojogja** [amchess/BrainLearn#15]
EvalFile Option to use NN.bin not showing on CLI & GUI

![no-evalfile](https://user-images.githubusercontent.com/20923433/89730960-9d165b80-da6d-11ea-85bf-06f2cf03d415.jpg)

**Comment by jackindojogja** [comment]
seem only sse42 binary no EvalFile option

**Comment by amchess** [comment]
You're right.
Thanks.
Now, I'm in holidays.
I'll correct it.
