### ISSUE TITLE
Is the learning like Alphazero and Leela ?

### ISSUE THREAD

**Issue by tux90** [amchess/BrainLearn#2]

**Comment by amchess** [comment]
What are the exact conditions of the match?
BrainLearn plays agaisnt himself or what?
The learning is different from Alphazero: it requires less results, because it doesn't store entire game's history.

**Comment by amchess** [comment]
The two engines are aligned at the same Stockfish patch ?

**Comment by tux90** [comment]
please

I hope the learning will be improved , and more like alphazero chess/leela learning.

Also it not learn in the opening, etc etc , because on playchess i use no book, and other people use books there.
I am running agian  a new test,  and I use the same experience.bin not a new one it's  3.5 MB.size

Blitz 5m  
1   Eman 4.10 64-bit BMI2    +30  +9/=82/-1 54.35%   50.0/92
2   BrainLearn 4.1 64 BMI2   -30  +1/=82/-9 45.65%   42.0/92
93 games so far

stil it can not win only one win game :( it keep loose much.
