### ISSUE TITLE
Please explain it to me as if i was a child

### ISSUE THREAD

**Issue by nilslindemann** [amchess/BrainLearn#21]
Hello,

Let me steal your time for a moment. I have three questions:

First is regarding installation.

```
BrainLearn12.1-general-64.exe
BrainLearn12.1-x86-64.exe
BrainLearn12.1-x86-64-modern.exe
BrainLearn12.1-x86-64-sse3-popcnt.exe
BrainLearn12.1-x86-64-sse41-popcnt.exe
BrainLearn12.1-x86-64-ssse3.exe
```

These work on my computer, a 10+ years old 64 bit Medion Akoya, no graphics card. Which to use? I guess the choice is between modern and sse41-popcnt.

Second question is what does it do? Could you give an example where i can see the effect? When i press the stop button in Scid, while being at an analysis depth 20 and then i press start again it restarts at depth 15. I understood that it saves these results to disk and shows them? If not, what else does it do? Does it not affect the shown evaluation?

Third question is about the mechanism. Does it minmax the positions saved in the experience.bin? And if so, does it search for strongly connected components in the move graph of the current pawn/piece amount/castling rights structure? I guess not. I search for a long time for an engine like this. Too bad that it seemingly doesnt exist.

Greetings, Nils.

**Comment by amchess** [comment]
> 
> 
> Hello,
> 
> Let me steal your time for a moment. I have three questions:
> 
> First is regarding installation.
> 
> ```
> BrainLearn12.1-general-64.exe
> BrainLearn12.1-x86-64.exe
> BrainLearn12.1-x86-64-modern.exe
> BrainLearn12.1-x86-64-sse3-popcnt.exe
> BrainLearn12.1-x86-64-sse41-popcnt.exe
> BrainLearn12.1-x86-64-ssse3.exe
> ```
> 
> These work on my computer, a 10+ years old 64 bit Medion Akoya, no graphics card. Which to use? I guess the choice is between modern and sse41-popcnt.
> 
> Second question is what does it do? Could you give an example where i can see the effect? When i press the stop button in Scid, while being at an analysis depth 20 and then i press start again it restarts at depth 15. I understood that it saves these results to disk and shows them? If not, what else does it do? Does it not affect the shown evaluation?
> 
> Third question is about the mechanism. Does it minmax the positions saved in the experience.bin? And if so, does it search for strongly connected components in the move graph of the current pawn/piece amount/castling rights structure? I guess not. I search for a long time for an engine like this. Too bad that it seemingly doesnt exist.
> 
> Greetings, Nils.

1. modern is the best
2. it saves the learnt positions in the experience.bin file. A gui must be run in administrator mode
3. the learning mechanism is on the search function and the private application takes into account also positions structures/positional patterns.
Regards,
Andrea

**Comment by nilslindemann** [comment]
Thanks. I start to understand. It affects the shown eval and the moves it chooses but not the depth, ok. One last question, does it make a big difference for analysis to enable Q-learning?

Edit: Wow, it even has an online live book and live book contribute, and this just works. My moves are online. cool :-) Nice job! Docs could be simpler, but nice job.
