### ISSUE TITLE
Questions regarding experience.bin

### ISSUE THREAD

**Issue by nilslindemann** [amchess/BrainLearn#22]
I have some more questions:

* When I stop the engine, what does it write to the experience.bin? Just the position I was currently pondering, or all positions I pondered since I started it / all positions in the hash?
* What is better for learning, to go into lines or to ponder deep on the root position?
* Is Multi pv better for learning or to just ponder one line?
* Is it possible to merge two experience files? E.g. two or more people work on different positions using the engine and when they are done the two experience.bin files are merged to a new one which has the results from both analysis.
* Is there a maximum size of experience.bin or is the available space on the computer the only barrier?

**Comment by amchess** [comment]
1. all positions
2. you can use standard learning  in infinite analysis and Q-learning to go into lines (play against itself)
3. better ponder oneline
3.yes
4. the barrier is the available space and ram on the computer

**Comment by nilslindemann** [comment]
hi @amchess, thanks for your answers. Have enabled Q-Learning now.

I just see in the docs that it automatically merges _experience[number].bin_ files to a single _experience.bin_ file. I have misread that.

I have many more questions but i will first look if the source code answers them for me :-)
