### ISSUE TITLE
It seems not to remember the results after a restart

### ISSUE THREAD

**Issue by nilslindemann** [amchess/BrainLearn#23]
I wondered why I don't get to 0.0 even after hours and hours of analyzing, so I tested with a study, it is this one:

`r4B1k/3p2Rp/7K/2pp4/1q3pBp/1N4b1/4R3/4r3 w - - 0 1`

White draws.

The solution is 1.Be6! (threatens Rg8 mate) dxe6 2.Bd6! (threatens Rxh7+-g7+ perpetual) Qc3 3.Nd4! Qxd4 4.Re5! Qd3! 5.Re4! Qc3! 6.Rd4! Qc2! 7.Rd3! Qb2! 8.Rc3! Qb1! 9.Rc2! Qa1! 10.Rb2! Qxb2 11.Be5 Qb7 12.Rxg3+ Qg7+ 13.Rxg7 Rxe5 14.
Rg8+ Rxg8 stalemate.

Stockfish 12 needs to ponder until depth 38 to find the solution, but of course forgets all results after a restart.

Some observations when analyzing with BrainLearn:

* Q-Learning seems to speed up the process.
* NNUE evaluation constantly flip-flops and needs to be disabled to get a stable 0.0 evaluation. E.g., this happens when navigating between the start position and the position after 1.Be6. It shows a clear black advantage in the start position and 0.0 in the position after 1.Be6. When I navigate back, it shows a clear advantage again (and suggests 1.Bd6). When I do this repeatedly, it sometimes also forgets the evaluation of the position after 1.Be6 and shows a clear black advantage again. I observe this behavior both with Stockfish and BrainLearn, so I guess it is a bug in the Stockfish NNUE code. This is the typical Stockfish evaluation flip-flopping I observe all the time during analysis. It is very frustrating.
* No matter how deep I let BrainLearn ponder on any position in that study, when I quit (not just stop) it when it shows 0.0 and restart it again, it doesn't immediately show 0.0 in the start position (meanwhile it does so at depth 23 but not before). I tried to let it ponder until depth 60 in my tests, no result. That way, I obviously can not permanently solve an opening. Yes, it tries different moves, which is cool, but then it flip-flops and goes back to the other line which it already analyzed to 0.0. Also, it sometimes starts to suggest moves with a worse evaluation than those which lead to a clear 0.0 evaluation.

The engine settings are: Hash 128 (I also tried with bigger hashes), one variation PV, two threads, syzygy path set (3-4-5 pieces), use Q-Learning (also tested without Q-Learning), don't use NNUE (also tested with NNUE), don't use Live book.

The GUI is Scid, which sends `position fen [a fen]` commands, but I also tested with ChessBase which sends `position startpos moves [some moves]` commands (which is better because it doesn't move back and forth showing an advantage for one side). The result is the same, it can not remember the 0.0 evaluation for the start position.

The current experience.bin containing just the moves posted above, is attached (rename it to _experience.bin_, GitHub doesn't allow uploads of *.bin files).

[experience.txt](https://github.com/amchess/BrainLearn/files/5631548/experience.txt)

So, after being enthusiastic at the start, I am now skeptical about the usefulness of this approach for analysis. If I can't get permanently to 0.0 with a decent amount of work, then it makes no sense. Then I better invest the time in learning how to defend worse endgames.

For analysis, it doesn't matter how pretty the moves are, what I need is a 0.0 evaluation for my black openings as quick as possible. First solve the fundamental problems, then let's look if we can squeeze out more. An engine which can't do that is not the right tool for solving chess.

Greetings, Nils (user schachnils at Lichess)

**Comment by amchess** [comment]
The learning is not immediate: there is an initial noise

**Comment by nilslindemann** [comment]
Sorry if I sounded harsh. I am amazed that people can program such stuff, which is like black magic to me.

**Comment by nilslindemann** [comment]
Just tested this with version 15.1. It still does not remember 1.Be6 and its evaluation 0.00.

**Comment by amchess** [comment]
now it's correctd

**Comment by nilslindemann** [comment]
I can not reproduce this. I still get no 0.00 with the latest version (BrainLearn18-x86-64-modern.exe), default settings. Tested on ChessBase 11 and Scid 4.7.0 on Windows 7. After I reach 0.00 and then close and re-open the engine, it has forgotten the evaluation again. What are your settings, please.

**Comment by nilslindemann** [comment]
I also tried it with a binary successfully compiled from the current codebase under Linux Mint 20.3 (I did [this](https://stackoverflow.com/questions/11471690/curl-h-no-such-file-or-directory/11471743#11471743) and [this](https://github.com/amchess/BrainLearn/issues/17#:~:text=you%20have%20to%20eliminate%20-lws2_32%20to%20compile%20on%20linux) and then ran `.\configure` and `make` and `make -j build ARCH=x86-64`).

Then I registered the created binary in Scid 4.7.0 (on Linux Mint) and then:

* In Scid, I set up the study from above - `r4B1k/3p2Rp/7K/2pp4/1q3pBp/1N4b1/4R3/4r3 w - - 0 1`.
* I start BrainLearn (no _experience.bin_. BrainLearn logs to an empty log file, which I later rename to _01-debug.log.txt_).
* I go into lines by entering the correct moves.
* After _1.Be6! dxe6 2.Bd6 Qc3 3.Nd4! Qxd4 4.Re5! Qd3 5.Re4 Qc3 6.Rd4 Qc2 7.Rd3 Qb2 8.Rc3 Qb1 9.Rc2_, BrainLearn detects the stalemate trap and switches to a 0.00 evaluation. See line 1074 in _01-debug.log.txt_: `info depth 14 seldepth 24 multipv 1 score cp 0 nodes 103040 nps 453920 tbhits 0 time 227 pv b1a1 c2b2 e1g1 g7h7 h8g8 h7g7 g8h8`.
* I then slowly navigate back to the position before _1.Be6!_ and it shows 0.00 all the time. See line 3674: `info depth 40 seldepth 19 multipv 1 score cp 0 nodes 1158808 nps 267746 hashfull 55 tbhits 0 time 4328 pv g4e6 d7e6 f8d6 b4c3 b3d4 c3d4 e2e5 d4d3 e5e4 d3e4 d6e5 a8a7 g7g4 a7g7 g4g7 e4e5 g7g8 h8g8`.
* I then close BrainLearn and Scid. The _experience.bin_ gets created.
* I move the _debug.log_ to another directory and rename it to _01-debug.log.txt_.
* I make a copy of the _experience.bin_ into another directory and rename it to _01-experience.bin.txt_.
* I restart Scid and let BrainLearn ponder on the position before _1.Be6!_ (logging into a new _debug.log_, now using the created _experience.bin_).
* BrainLearn ponders on _1.Be6!_ from depth 11 to 18, see line 118 in _02-debug.log.txt_, but it does not give 0.00.
* On depth 19, line 177, it switches to _1.Bd6?_. The wrong solution, as after _1...Qc3! 2.Re5 Qxe5! 3.Bxe5 Rxe5_ there is no stalemate and there are too many black pawns.
* On depth 25, line 940, it switches to _1.Be6!_ again, but it does not give a 0.00 evaluation.
* On depth 28, line 1660, it then switches back to _1.Bd6?_ and stays there until depth 31.
* After that I close Scid, as my Linux Laptop tends to shut down due to overheating.
* I rename the _experience.bin_ to _02-experience.bin.txt_ and the _debug.log_ to _02-debug.log.txt_.

Here these four files:

[01-debug.log.txt](https://github.com/amchess/BrainLearn/files/9299689/01-debug.log.txt)
[01-experience.bin.txt](https://github.com/amchess/BrainLearn/files/9299690/01-experience.bin.txt)
[02-debug.log.txt](https://github.com/amchess/BrainLearn/files/9299691/02-debug.log.txt)
[02-experience.bin.txt](https://github.com/amchess/BrainLearn/files/9299692/02-experience.bin.txt)

So, all in all, I am not able to make BrainLearn show _1.Be6_ permanently, and if it does for a short while, it does not give an evaluation of 0.00, unless I help by going into lines.

**Comment by amchess** [comment]
You have to give the time to the engine.
Use the formula M=2nft to correctly setup the ram for hash tables and the average time in seconds per move.

**Comment by nilslindemann** [comment]
Can you give an example? In the above test I used 128 Megabyte Hash and one Processor (50% of processing power). How long do I have to let BrainLearn ponder per move in that case?

Can you define _M_, _n_, _f_ and _t_ in this formula? I guess _M_ is the hash in Megabyte, _n_ the kilonodes per second, and _t_ the pondertime in seconds? What is _f_?

**Comment by amchess** [comment]
+M=hash size in kb (it must always be a 2 power and not superior to half of your ram size)
n=threads number. A good advice is to setup only real cores on a laptop and real+logical-2 on a desktop (2 for the OS)
f=clock frequency in Mhz
t=average time in seconds per move (a blitz is more or less 10 seconds)

**Comment by nilslindemann** [comment]
Hello again, thanks for the definitions.

So, according to that formula, if I use a hash of 64 MB and 2 threads on a computer with 2.3 GHz clock, I should let it ponder a bit more than 7 seconds at least, right? (64 * 1024 / (2 * 2) / (2.3 * 1000) = 7.1) I notice that this ponder time usually leads to approximately 30% to 50% hash full on a position (Scid shows this when the "show engine info" button is pressed). Is this value an indicator that the engine has pondered enough?

I have tested it on the above study, letting it ponder on each position until hash 100% full (then pressing stop to save the info to the experience.bin). After some back and forth, it shows 0.00 on the start position, and I stop the engine (UCI stop command) to save the info.

But as soon as I completely restart the engine (UCI quit command and restart), the information is lost. Sometimes it shows 1.Be6 for a while, but with the wrong evaluation, then it switches back to the losing move 1.Bd6?

It needs to ponder until approximately depth 40 to find 1.Be6! 0.00 (as Stockfish also does).

Have you succeeded in getting a 0.00 evaluation on the start position relatively immediately and permanently? Is this possible at all? Or do I misunderstand what this engine wants to do?

**Comment by amchess** [comment]
This is your experience opened with our ExperienceManagement application:
![image](https://user-images.githubusercontent.com/10925308/184237168-578e282e-05f8-4dd9-8f75-927d7f99505e.png)
This is your experience file. It has Be6 with correct evaluation at depth 46
From the search.cpp, you have
        if (learningMove)
        {
            assert(sibs);
            enabledLearningProbe = true;
So, you have to wait a littlle to have the right move because at the begin, the engine probe Bd6 till depth 27.
Surely, it arrives to Be6 by using a lot less time.
You can see yourself by analyzing with or without your exp file.

**Comment by nilslindemann** [comment]
Hi again,

Thanks for the further explanation. Which software is this, which you use in the screenshot? Can it be downloaded somewhere?

Meanwhile, I have been able once to make it so that BrainLearn shows _1.Be6 0.00_ all the time. But I do not know how I did this, and I can not reproduce it. [I created a video which shows how it usually behaves](https://www.youtube.com/watch?v=oVVtubV9pGU). BrainLearn learns _1.Be6_ indeed and shows it after a few seconds, but on greater depths the evaluation goes down. See [this moment of the video](https://youtu.be/oVVtubV9pGU?t=682) where I reopen BrainLearn. Also, I seem to have to go into lines twice before BrainLearn learns the moves.

All in all,

* It is cool that BrainLearn can learn such things and show the move quite fast.
* Still, the learning seems to be a bit wobbly. I don't know how exactly I have to enter such moves in order for BrainLearn to learn them.
* I would like if BrainLearn could immediately show the entry of the experience.bin with the highest depth. I am fine if it ponders other things in the background, but I am interested in the saved move with the highest depth. An idea would be to show that move as the second variation, when one enables _multipv 2_, and the first variation shows what BrainLearn actually ponders. Just an idea.

**Comment by nilslindemann** [comment]
closing this.

**Comment by nilslindemann** [comment]
well, now.

**Comment by amchess** [comment]
I take into account.
The exprienceManagement is here:
https://gitlab.com/amchess/experiencemanagement/-/tags/1.0

**Comment by nilslindemann** [comment]
Thank you for the link.
