### ISSUE TITLE
What is BrainLearn DGV?

### ISSUE THREAD

**Issue by magicianfromriga** [amchess/BrainLearn#25]
Hi, I just wanted to ask - what is the difference between BrainLearn 13 and BrainLearn DGV? Also, how much of a strength drop can be expected when using MCTS? I want to optimise my performance for correspondence chess, where priority is long thinks.

**Comment by amchess** [comment]
It's a data generation and validation to generate and validate training data for new net or reinforce existing ones, also based on the experience file.

**Comment by amchess** [comment]
Single MCTS is a little stronger than Multi one and both are a little worse than standard, but they can be used as another advise on particular positions.
For correspondence chess, use the engine with Opening Variety to 20 and setup correctly threads, Hashtables size and sygyzy parameters. In analysis mode, use contempt = 0 and dynamic contempt to off. This to have a meaningful value of the score showed by the gui.
Also ShashChess is very useful for corr chess.

**Comment by magicianfromriga** [comment]
How do we use DGV then? Will it work as a normal engine or do we need to do something special with it?
I use ShashChess already, I usually set threads=12 (the max in my processor), full depth threads= 6 to 10, hash=1024 (RAM is 8GB, in rare cases I set to 4192 which is the max allowed hash). I have 5 piece Sygzgy as my SSD is not big enough for 6 piece. Contempt and dynamic contempt is always set to off. Please do comment on this configuration.
I have seen that MCTS engines have a wider 'error' range in that they feel a lot more openings are playable. Since I hit depths anywhere from 50 (bare minimum) to 75(a day long think), can I get away with using MCTS all the time or would you advise greater variety (getting one engine to use MCTS and the other not using it)? Would this depth be sufficient?
Also, I created a PGN to create an experience file. It had around 6 million games, mostly engine, correspondence and GM+ players playing each other. Would the CuteChess settings that you have given work for the same? What would you suggest I do to make the experience and thus the engine stronger?

**Comment by amchess** [comment]
There are instructions to generate and validate training data in the branch's docs folder.
For the experience, the best should be a one on all eco codes, but it needs time and a collaborative work.
Regards,
Andrea

**Comment by magicianfromriga** [comment]
Hi,
Thanks for the advice. So it's more about variety than precision? Will Lichess games between masters help?

**Comment by amchess** [comment]
Opening variety is an option varying from 0 to 40.
Its goal is to provide opening variety in playing.
At 40, you'll have a little elo loss, but at 20, it's ideal because you won't have elo loss, but
a variety of play.

**Comment by magicianfromriga** [comment]
Hi,
I tried RL by creating Training data. It took almost a day and a half for 2 million sfens. Also, the number of sfens generated per second is really low - 46 per second. Is there an issue with my system? I was using all 12 threads on an I7-9750H.

**Comment by amchess** [comment]
No: it's normal a similar speed on your system.
Training data generation is a very hard process.

**Comment by magicianfromriga** [comment]
Ok, thanks for answering my questions!
Wish you luck in your engine development!

**Comment by amchess** [comment]
thanks
