### ISSUE TITLE
Concurrent experience

### ISSUE THREAD

**Issue by shapiro85** [amchess/BrainLearn#27]
Merry Christmas to you and your family. May your year be full of blessings and happiness.
thank you very much for the great work on Learning Algorithm .
How we can merge hundreds ( I have few thousands) files of  experience after running BrainLearn with Concurrent experience enabled to test it against other engines.
if it is not possible now could you please consider making a tool or command line in the future

**Comment by amchess** [comment]
Thanks. Also to you.
I strongly recommend to not use the concurrent experience, but to keep separate the clone engines in separated folder and merge at the end the files.
To merge the files, follow the procedure illustrated in readme file.
