### ISSUE TITLE
Tool for Experience file

### ISSUE THREAD

**Issue by taniaMashenko** [amchess/BrainLearn#28]
Dear K. Kiniama, A. Manzo  ,
Thank you very for adding learning ability to Stockfish
Could you please, please ( If it's not too much trouble ) ad some tools , utility or command lines to view and edit the exp file.
this will be great help when merging the exp files to check which 1 is better

best wishes
Tania

**Comment by amchess** [comment]
https://gitlab.com/amchess/experiencemanagement
