### ISSUE TITLE
Show the deepest entry of the experience.bin as the second line in multi ponder variation mode

### ISSUE THREAD

**Issue by nilslindemann** [amchess/BrainLearn#29]
I kindly request the following feature:

When the user sends [set option multipv 2](http://wbec-ridderkerk.nl/html/UCIProtocol.html#:~:text=multipv), BrainLearn keeps pondering on just one move and shows the results in the first variation. In the second variation BrainLearn shows the current move from the experience.bin with the highest depth.

For example, if BrainLearn ponders on 1.c4 and the experience.bin contains 1.e4 depth 32, and 1.d4 depth 35. BrainLearn shows 1.c4 as pv 1 and 1.d4 as pv 2.

Some GUIs may make problems if the two moves in pv1 and pv2 are the same, so let this be an option which can be disabled.

**Comment by amchess** [comment]
It could be an idea, even if with the experience management you have all infos about the experience on a position

**Comment by nilslindemann** [comment]
I would like it in the engine output, because then it would be all in one place. I would not have to switch back and forth between windows. Also, the display in the java app does not auto-update, and the experience.bin has to be reloaded manually, so this is a bit clunky.

I have just looked a bit at the code. Not that I understood very much, but it seems that it just updates the experience.bin when the engine is quitted, not just stopped, right?

My wet dream would be that I could just stop (not quit) the engine while analyzing in multipv 2 mode (which means BrainLearn actually analyzes in multipv 1 mode), and then it writes its knowledge to the experience.bin. Then, when I restart, I can see the (maybe new) deepest entry in the pv2 line. That would be the optimal flow for analysis, you know, direct feedback.

Of course, this is just a request. If this is too hard to implement and/or takes too much time, please dont mind. I know, the problems often are the details.

**Comment by nilslindemann** [comment]
I am currently simulating this behavior in a software called Chess Position Trainer (which even can min max), but I actually prefer the Scid GUI because it is more flowy. Mouse wheel works, it's responsive, one-click move entry, auto updating database view, etc.

**Comment by amchess** [comment]
> I would like it in the engine output, because then it would be all in one place. I would not have to switch back and forth between windows. Also, the display in the java app does not auto-update, and the experience.bin has to be reloaded manually, so this is a bit clunky.
> 
> I have just looked a bit at the code. Not that I understood very much, but it seems that it just updates the experience.bin when the engine is quitted, not just stopped, right?
> 
> My wet dream would be that I could just stop (not quit) the engine while analyzing in multipv 2 mode (which means BrainLearn actually analyzes in multipv 1 mode), and then it writes its knowledge to the experience.bin. Then, when I restart, I can see the (maybe new) deepest entry in the pv2 line. That would be the optimal flow for analysis, you know, direct feedback.
> 
> Of course, this is just a request. If this is too hard to implement and/or takes too much time, please dont mind. I know, the problems often are the details.

Yes, right.
I'm in doubt if to implement it because I released the desktop application just for this.
Andrea

**Comment by nilslindemann** [comment]
I will close this, as you indicated that you do not want to do it. But thanks for considering it.
