### ISSUE TITLE
Analysis not showing in Aquarium

### ISSUE THREAD

**Issue by belgiantaff** [amchess/BrainLearn#33]
### Describe the issue

Versions 26.3 and 26.4 do not seem to work in AQ - analysis starts but fails to display, and zero depth noted. Conversely, version 26.2, with identical parameters, works well. Any clue as to how to fix please?

### Expected behavior

after a few seconds of running the engine I'd expect the analysis to be shown and continueupdating until stopped.

### Steps to reproduce

![image](https://github.com/amchess/BrainLearn/assets/69969779/b42b8b5c-8b1f-4f0d-942e-cd1d17eb284d)

### Anything else?

Display is as:

![image](https://github.com/amchess/BrainLearn/assets/69969779/46e6f746-c2ba-42f9-98b3-3347f453c463)

### Operating system

Windows

### Brainlearn version

Brainlearn 26.4

**Comment by amchess** [comment]
The problem is the option UCI_ShowWDL, now at true.
Aquarium doesn't support the win probability visualisation.
So, if you want the analysis showed you have to uncheck it.

**Comment by belgiantaff** [comment]
Yes, that solves it. Many thanks!

 

Paul
