### ISSUE TITLE
Learning switch

### ISSUE THREAD

**Issue by shapiro85** [amchess/BrainLearn#7]
Thank you very much for adding the learning function to SF,
Could you please add the on/off switch
on learning read and write
off just read only
this will be very useful when you run bullets tournaments or testing some opening books.
this way the engine will use the info from exp.bin without messing up the learning files

**Comment by amchess** [comment]
This is not a priority, but very easy to implement.
So, I consider it for the next version.
Thanks.

**Comment by shapiro85** [comment]
Thank you for the reply,
I am looking forward to the next update
