### ISSUE TITLE
Error in Compiling: curl.h

### ISSUE THREAD

**Issue by VezirChess** [amchess/BrainLearn#8]
There is an error on compiling BrainLearn which is caused by livebook's curl.h

 curl/curl.h: No such file or directory
   44 | #include <curl/curl.h>

**Comment by thaichessswinboard** [comment]
you can delete all curl on search.cpp and g_inbook AND THEN GO TO EDIT MAKEFILE THEN // lcurl SOMETHING AND SAVE FILE THEN COMPILE IT WILL WORK.

**Comment by thaichessswinboard** [comment]
Brain learn 8.0 it good source code can play with stockfish and make good result. Thanks for make good engine for us to learn about good chess engines.

**Comment by amchess** [comment]
Closed
